### ISSUE TITLE
Unable to save changes, and the extension is not running

### ISSUE THREAD

**Issue by Cornelius7C5** [brpaz/ulauncher-docsearch#7]
I'm getting the error below. As in the title, I'm unable to save any changes and to even use the extension fresh after installing it.
```
Message: 'com.github.brpaz.ulauncher-docsearch'
Error Name: UnhandledError
Type: KeyError

Stacktrace:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 433, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-docsearch'

```

**Comment by brpaz** [comment]
This error generally indicates that you have a missing python package on your system. Please check if you have installed algolia package as specified in the README. The latest versions of Ulauncher also displays a when he there is a missing package when in the extension settings.
